/** M2 pipeline fixture adapters reuse the same source bytes as the isomorphic package suites. */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { REPO_ROOT } from '../paths.ts';
import { IRIDIUM_FIXTURE_VERSION } from './index.ts';

/** A named note fixture ready to create through the product's note API. */
export interface MarkdownFixture {
  readonly id: string;
  readonly markdown: string;
}

/** Generated pathological text and its declared worker/admission outcome. */
export interface PathologicalMarkdownFixture extends MarkdownFixture {
  readonly status: string;
  readonly detail?: string;
}

/** Invalid committed fixture data is a repository error with a concrete correction path. */
export class MarkdownFixtureFormatError extends Error {
  constructor(path: string) {
    super(`Markdown fixture ${path} has an invalid shape; repair the committed corpus descriptor.`);
    this.name = 'MarkdownFixtureFormatError';
  }
}

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function entries(relative: string): { path: string; values: unknown[] } {
  const path = join(REPO_ROOT, 'packages', 'markdown', 'fixtures', relative);
  const value: unknown = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(value)) throw new MarkdownFixtureFormatError(path);
  return { path, values: value };
}

function sources(relative: string): MarkdownFixture[] {
  const corpus = entries(relative);
  return corpus.values.map((value: unknown) => {
    if (!record(value) || typeof value.id !== 'string' || typeof value.source !== 'string')
      throw new MarkdownFixtureFormatError(corpus.path);
    return { id: value.id, markdown: value.source };
  });
}

/** Golden GFM notes are the same source the parser, preview and projection snapshots exercise. */
export function readMarkdownGoldenFixtures(): readonly MarkdownFixture[] {
  const root = join(REPO_ROOT, 'packages', 'markdown', 'fixtures', 'golden');
  const path = join(root, 'manifest.json');
  const manifest: unknown = JSON.parse(readFileSync(path, 'utf8'));
  if (
    !record(manifest) ||
    manifest.fixtureVersion !== IRIDIUM_FIXTURE_VERSION ||
    typeof manifest.pipelineVersion !== 'number' ||
    !Number.isSafeInteger(manifest.pipelineVersion) ||
    manifest.pipelineVersion < 1 ||
    !record(manifest.files)
  )
    throw new MarkdownFixtureFormatError(path);
  for (const [file, hash] of Object.entries(manifest.files)) {
    if (
      !/^[a-z0-9.-]+$/i.test(file) ||
      createHash('sha256').update(readFileSync(join(root, file))).digest('hex') !== hash
    )
      throw new MarkdownFixtureFormatError(join(root, file));
    if (file.endsWith('.projection.json')) {
      const projection: unknown = JSON.parse(readFileSync(join(root, file), 'utf8'));
      if (!record(projection) || projection.pipelineVersion !== manifest.pipelineVersion)
        throw new MarkdownFixtureFormatError(join(root, file));
    }
  }
  return sources('golden/sources.json');
}

/** Additional scheme-smuggling, HTML and footnote vectors complement the original hostile corpus. */
export function readMarkdownHostileFixtures(): readonly MarkdownFixture[] {
  return sources('hostile/sources.json');
}

/** Expands compact descriptors deterministically; no hostile input is generated by a product parser. */
export function readMarkdownPathologicalFixtures(): readonly PathologicalMarkdownFixture[] {
  const corpus = entries('pathological/cases.json');
  return corpus.values.map((value: unknown) => {
    if (
      !record(value) ||
      typeof value.id !== 'string' ||
      typeof value.repeat !== 'string' ||
      typeof value.count !== 'number' ||
      !Number.isSafeInteger(value.count) ||
      value.count < 0 ||
      typeof value.status !== 'string' ||
      (value.suffix !== undefined && typeof value.suffix !== 'string') ||
      (value.detail !== undefined && typeof value.detail !== 'string')
    ) {
      throw new MarkdownFixtureFormatError(corpus.path);
    }
    return {
      id: value.id,
      markdown: value.repeat.repeat(value.count) + (value.suffix ?? ''),
      status: value.status,
      ...(typeof value.detail === 'string' ? { detail: value.detail } : {}),
    };
  });
}
