/** Attachment operations added by M2; the route index and HTTP registrations share these rows. */
import { ATTACHMENT_TYPES } from '../attachments.ts';
import {
  Attachment,
  AttachmentPage,
  AttachmentParams,
  AttachmentUploadBody,
  AttachmentUploaded,
  DeleteAttachmentQuery,
  ListAttachmentsQuery,
  UnreferencedAttachmentPage,
  UnreferencedAttachmentsQuery,
} from './attachments.ts';
import { ClientHeaders, IfMatchHeaders } from './common.ts';
import { VaultIdParams } from './params.ts';
import { REST_ROUTE_POLICIES } from './route-policies.ts';
import type { RouteSpec } from './routes.ts';

/** The five vault operations and administrator report. */
export const M2_ATTACHMENT_ROUTES: readonly RouteSpec[] = [
  {
    operationId: 'attachments.list',
    method: 'GET',
    path: '/vaults/:vaultId/attachments',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'attachments',
    auth: REST_ROUTE_POLICIES['attachments.list'],
    request: { params: VaultIdParams, query: ListAttachmentsQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: AttachmentPage } }],
    errors: ['unauthenticated', 'token_expired', 'not_found', 'validation_failed'],
    rateLimit: 'pat',
    summary: 'List attachment metadata and optional live references.',
  },
  {
    operationId: 'attachments.upload',
    method: 'POST',
    path: '/vaults/:vaultId/attachments',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'attachments',
    auth: REST_ROUTE_POLICIES['attachments.upload'],
    request: { params: VaultIdParams, body: AttachmentUploadBody, headers: ClientHeaders },
    responses: [
      {
        status: 201,
        body: { kind: 'json', schema: AttachmentUploaded },
        location: '/api/v1/vaults/<vaultId>/attachments/<id>/meta',
      },
    ],
    errors: [
      'unauthenticated',
      'forbidden',
      'csrf_rejected',
      'not_found',
      'name_conflict',
      'vault_archived',
      'unsupported_media',
      'validation_failed',
      'rate_limited',
      'capacity',
    ],
    summary: 'Stream, sniff and deduplicate exactly one multipart attachment.',
  },
  {
    operationId: 'attachments.download',
    method: 'GET',
    path: '/vaults/:vaultId/attachments/:attachmentId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'attachments',
    auth: REST_ROUTE_POLICIES['attachments.download'],
    request: { params: AttachmentParams },
    responses: [
      {
        status: 200,
        body: { kind: 'binary', contentTypes: Object.keys(ATTACHMENT_TYPES) },
        etag: 'strong-hash',
      },
      {
        status: 206,
        body: { kind: 'binary', contentTypes: Object.keys(ATTACHMENT_TYPES) },
        etag: 'strong-hash',
      },
      { status: 304, body: { kind: 'empty' }, etag: 'strong-hash' },
    ],
    errors: ['unauthenticated', 'token_expired', 'not_found', 'validation_failed'],
    rateLimit: 'pat',
    summary: 'Read immutable attachment bytes with safe disposition and single-range support.',
    problemVariants: ['attachment-range', 'attachment-missing'],
  },
  {
    operationId: 'attachments.getMeta',
    method: 'GET',
    path: '/vaults/:vaultId/attachments/:attachmentId/meta',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'attachments',
    auth: REST_ROUTE_POLICIES['attachments.getMeta'],
    request: { params: AttachmentParams },
    responses: [
      { status: 200, body: { kind: 'json', schema: Attachment }, etag: 'strong-version' },
    ],
    errors: ['unauthenticated', 'token_expired', 'not_found'],
    rateLimit: 'pat',
    summary: 'Read attachment metadata and its deletion validator.',
  },
  {
    operationId: 'attachments.delete',
    method: 'DELETE',
    path: '/vaults/:vaultId/attachments/:attachmentId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'attachments',
    auth: REST_ROUTE_POLICIES['attachments.delete'],
    request: { params: AttachmentParams, query: DeleteAttachmentQuery, headers: IfMatchHeaders },
    responses: [{ status: 204, body: { kind: 'empty' } }],
    errors: [
      'unauthenticated',
      'forbidden',
      'csrf_rejected',
      'not_found',
      'attachment_referenced',
      'stale_version',
      'vault_archived',
      'precondition_required',
      'validation_failed',
    ],
    ifMatch: 'required',
    summary: 'Soft-delete an attachment; referenced files require force=true.',
  },
  {
    operationId: 'admin.attachments.unreferenced',
    method: 'GET',
    path: '/admin/attachments/unreferenced',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'admin',
    auth: REST_ROUTE_POLICIES['admin.attachments.unreferenced'],
    request: { query: UnreferencedAttachmentsQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: UnreferencedAttachmentPage } }],
    errors: ['unauthenticated', 'forbidden', 'validation_failed', 'unavailable'],
    summary: 'Read the last completed report of attachments unused by live or retained content.',
  },
];
