/** The M2 tree/lifecycle and vault metadata route manifest (09-api-reference.md §2.5, §2.7). */
import type { ErrorCode } from '../errors.ts';
import { IfMatchHeaders, Node, Vault } from './common.ts';
import { NoteIdParams, VaultIdParams } from './params.ts';
import { REST_ROUTE_POLICIES } from './route-policies.ts';
import type { RouteSpec } from './routes.ts';
import {
  InboundLinksPage,
  ListChildrenQuery,
  ListInboundLinksQuery,
  ListNodesQuery,
  ListTrashQuery,
  NodeIdParams,
  NodePage,
  NodePatchResult,
  PatchNodeBody,
  PurgeNodeQuery,
  RestoreNodeBody,
  RestoreNodeResult,
  TrashNodeBody,
  TrashNodeResult,
  TrashPage,
  TreePage,
  RenameImpactQuery,
  RenameImpactResult,
} from './tree.ts';
import { ConfirmVaultBody, PatchVaultBody } from './vaults.ts';

const STRUCTURAL_ERRORS: readonly ErrorCode[] = [
  'unauthenticated',
  'forbidden',
  'csrf_rejected',
  'not_found',
  'stale_version',
  'name_conflict',
  'invalid_move',
  'invalid_state',
  'vault_archived',
  'validation_failed',
  'precondition_required',
];

/** Additional M2 operations; the existing nodes.create operation widens its owned request schema. */
export const M2_TREE_ROUTES: readonly RouteSpec[] = [
  {
    operationId: 'notes.renameImpact',
    method: 'GET',
    path: '/notes/:noteId/rename-impact',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'notes',
    auth: REST_ROUTE_POLICIES['notes.renameImpact'],
    request: { params: NoteIdParams, query: RenameImpactQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: RenameImpactResult } }],
    errors: ['unauthenticated', 'not_found', 'invalid_move', 'validation_failed'],
    summary: 'Preview a proposed note path and its link impact without write permission.',
  },
  {
    operationId: 'tree.listChildren',
    method: 'GET',
    path: '/vaults/:vaultId/tree',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['tree.listChildren'],
    request: { params: VaultIdParams, query: ListChildrenQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: TreePage } }],
    errors: ['unauthenticated', 'not_found', 'validation_failed'],
    summary: 'One live parent and its children, categories first, with natural name ordering.',
  },
  {
    operationId: 'nodes.list',
    method: 'GET',
    path: '/vaults/:vaultId/nodes',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.list'],
    request: { params: VaultIdParams, query: ListNodesQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: NodePage } }],
    errors: ['unauthenticated', 'token_expired', 'forbidden', 'not_found', 'validation_failed'],
    rateLimit: 'pat',
    summary: 'Derived paths and committed summaries, with history authorization for trashed nodes.',
  },
  {
    operationId: 'nodes.get',
    method: 'GET',
    path: '/nodes/:nodeId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.get'],
    request: { params: NodeIdParams },
    responses: [{ status: 200, body: { kind: 'json', schema: Node }, etag: 'strong-version' }],
    errors: ['unauthenticated', 'not_found'],
    summary: 'One live or trashed node with its derived path and current version.',
  },
  {
    operationId: 'nodes.update',
    method: 'PATCH',
    path: '/nodes/:nodeId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.update'],
    request: { params: NodeIdParams, body: PatchNodeBody, headers: IfMatchHeaders },
    responses: [
      { status: 200, body: { kind: 'json', schema: NodePatchResult }, etag: 'strong-version' },
    ],
    errors: [...STRUCTURAL_ERRORS, 'node_trashed'],
    ifMatch: 'required',
    summary:
      'Rename or move a node, or preview the same validation and link impact without writes.',
  },
  {
    operationId: 'nodes.trash',
    method: 'POST',
    path: '/nodes/:nodeId/trash',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.trash'],
    request: { params: NodeIdParams, body: TrashNodeBody, headers: IfMatchHeaders },
    responses: [{ status: 200, body: { kind: 'json', schema: TrashNodeResult } }],
    errors: [...STRUCTURAL_ERRORS, 'category_not_empty'],
    ifMatch: 'required',
    summary: 'Trash a node and, when explicitly recursive, its live descendants.',
  },
  {
    operationId: 'nodes.restore',
    method: 'POST',
    path: '/nodes/:nodeId/restore',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.restore'],
    request: { params: NodeIdParams, body: RestoreNodeBody, headers: IfMatchHeaders },
    responses: [{ status: 200, body: { kind: 'json', schema: RestoreNodeResult } }],
    errors: STRUCTURAL_ERRORS,
    ifMatch: 'required',
    summary:
      'Restore one cascade group or a selected member, resolving name and parent conflicts explicitly.',
  },
  {
    operationId: 'nodes.purge',
    method: 'DELETE',
    path: '/nodes/:nodeId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.purge'],
    request: { params: NodeIdParams, query: PurgeNodeQuery, headers: IfMatchHeaders },
    responses: [{ status: 204, body: { kind: 'empty' } }],
    errors: [...STRUCTURAL_ERRORS, 'step_up_required'],
    ifMatch: 'required',
    summary: 'Permanently delete a trashed subtree and its note rows; attachments are retained.',
  },
  {
    operationId: 'nodes.inboundLinks',
    method: 'GET',
    path: '/nodes/:nodeId/inbound-links',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['nodes.inboundLinks'],
    request: { params: NodeIdParams, query: ListInboundLinksQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: InboundLinksPage } }],
    errors: ['unauthenticated', 'not_found', 'validation_failed'],
    summary: 'Page the same target-side links that rename and move warnings summarize.',
  },
  {
    operationId: 'trash.list',
    method: 'GET',
    path: '/vaults/:vaultId/trash',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'nodes',
    auth: REST_ROUTE_POLICIES['trash.list'],
    request: { params: VaultIdParams, query: ListTrashQuery },
    responses: [{ status: 200, body: { kind: 'json', schema: TrashPage } }],
    errors: ['unauthenticated', 'forbidden', 'not_found', 'validation_failed'],
    summary: 'Newest-first trash groups with current validators; requires history:read.',
  },
  {
    operationId: 'vaults.update',
    method: 'PATCH',
    path: '/vaults/:vaultId',
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'vaults',
    auth: REST_ROUTE_POLICIES['vaults.update'],
    request: { params: VaultIdParams, body: PatchVaultBody, headers: IfMatchHeaders },
    responses: [{ status: 200, body: { kind: 'json', schema: Vault }, etag: 'strong-version' }],
    errors: [
      'unauthenticated',
      'forbidden',
      'csrf_rejected',
      'not_found',
      'stale_version',
      'name_conflict',
      'vault_archived',
      'validation_failed',
      'precondition_required',
    ],
    ifMatch: 'required',
    summary: 'Update vault metadata and settings while enforcing environment floors.',
  },
  ...(['vaults.archive', 'vaults.unarchive'] as const).map((operationId): RouteSpec => ({
    operationId,
    method: 'POST',
    path: `/vaults/:vaultId/${operationId === 'vaults.archive' ? 'archive' : 'unarchive'}`,
    mount: '/api/v1',
    plugin: 'rest',
    tag: 'vaults',
    auth: REST_ROUTE_POLICIES[operationId],
    request: { params: VaultIdParams, body: ConfirmVaultBody, headers: IfMatchHeaders },
    responses: [{ status: 200, body: { kind: 'json', schema: Vault }, etag: 'strong-version' }],
    errors: [
      'unauthenticated',
      'forbidden',
      'csrf_rejected',
      'not_found',
      'step_up_required',
      'invalid_state',
      'stale_version',
      'vault_archived',
      'validation_failed',
      'precondition_required',
    ],
    ifMatch: 'required',
    summary:
      operationId === 'vaults.archive'
        ? 'Freeze the vault for reading and close its collaboration sessions after commit.'
        : 'Return an archived vault to active use.',
  })),
];
