/**
 * The migration list compiled into the image.
 *
 * `/readyz` compares `kysely_migration` with this list and returns `503 {migrations:'pending'}`
 * while they differ, which is what makes readiness fail closed: a server whose schema is older
 * than its code never serves traffic (A7). That comparison has to be against a list the binary
 * carries, not against whatever `.ts` files happen to sit next to it, so the provider is a static
 * import map rather than a filesystem scan -- which also means the same list serves the bundled
 * `dist/main.mjs`, the in-process test harness and `kysely-ctl` without three ways to disagree.
 *
 * The order of the keys is the apply order, and it is the file order: zero-padded four digits,
 * then the object (03-data-model.md section 14.2).
 *
 * Generated by scripts, reviewed as source: adding a migration means adding its import and its
 * entry here, which is what makes a forgotten registration a type error rather than a silent skip.
 */
import type { Migration, MigrationProvider } from 'kysely/migration';

import * as m0001 from '../../migrations/0001_users.ts';
import * as m0002 from '../../migrations/0002_user_credentials.ts';
import * as m0003 from '../../migrations/0003_password_setup_tokens.ts';
import * as m0004 from '../../migrations/0004_sessions.ts';
import * as m0005 from '../../migrations/0005_login_throttle.ts';
import * as m0006 from '../../migrations/0006_vaults.ts';
import * as m0007 from '../../migrations/0007_vault_members.ts';
import * as m0008 from '../../migrations/0008_access_tokens.ts';
import * as m0009 from '../../migrations/0009_access_token_vaults.ts';
import * as m0010 from '../../migrations/0010_nodes.ts';
import * as m0011 from '../../migrations/0011_nodes_uq_sibling.ts';
import * as m0012 from '../../migrations/0012_trash_entries.ts';
import * as m0013 from '../../migrations/0013_notes.ts';
import * as m0014 from '../../migrations/0014_note_docs.ts';
import * as m0015 from '../../migrations/0015_note_updates.ts';
import * as m0016 from '../../migrations/0016_note_revisions.ts';
import * as m0017 from '../../migrations/0017_note_projections.ts';
import * as m0018 from '../../migrations/0018_note_projections_fm_indexes.ts';
import * as m0019 from '../../migrations/0019_note_search.ts';
import * as m0020 from '../../migrations/0020_note_search_fulltext.ts';
import * as m0021 from '../../migrations/0021_note_links.ts';
import * as m0022 from '../../migrations/0022_attachments.ts';
import * as m0023 from '../../migrations/0023_jobs.ts';
import * as m0024 from '../../migrations/0024_import_jobs.ts';
import * as m0025 from '../../migrations/0025_export_jobs.ts';
import * as m0026 from '../../migrations/0026_audit_events.ts';
import * as m0027 from '../../migrations/0027_audit_chain_heads.ts';
import * as m0028 from '../../migrations/0028_audit_events_triggers.ts';
import * as m0029 from '../../migrations/0029_audit_events_archive.ts';
import * as m0030 from '../../migrations/0030_access_log.ts';
import * as m0031 from '../../migrations/0031_server_settings.ts';
import * as m0032 from '../../migrations/0032_schema_meta.ts';
import * as m0033 from '../../migrations/0033_desktop_releases.ts';
import * as m0034 from '../../migrations/0034_grants.ts';
import * as m0035 from '../../migrations/0035_oauth_clients.ts';
import * as m0036 from '../../migrations/0036_oauth_clients_grants.ts';
import * as m0037 from '../../migrations/0037_oauth_consents.ts';
import * as m0038 from '../../migrations/0038_oauth_consents_uq_live.ts';
import * as m0039 from '../../migrations/0039_oauth_consents_grants.ts';
import * as m0040 from '../../migrations/0040_oauth_consent_vaults.ts';
import * as m0041 from '../../migrations/0041_oauth_consent_vaults_grants.ts';
import * as m0042 from '../../migrations/0042_oauth_authorization_codes.ts';
import * as m0043 from '../../migrations/0043_oauth_authorization_codes_grants.ts';
import * as m0044 from '../../migrations/0044_oauth_refresh_tokens.ts';
import * as m0045 from '../../migrations/0045_oauth_refresh_tokens_grants.ts';
import * as m0046 from '../../migrations/0046_access_tokens_oauth_columns.ts';
import * as m0047 from '../../migrations/0047_access_tokens_oauth_indexes.ts';
import * as m0048 from '../../migrations/0048_access_log_oauth_client.ts';
import * as m0049 from '../../migrations/0049_admin_users_lock.ts';
import * as m0050 from '../../migrations/0050_session_revocation_commands.ts';
import * as m0051 from '../../migrations/0051_session_revocation_commands_grants.ts';
import * as m0052 from '../../migrations/0052_collab_owner_fence.ts';
import * as m0053 from '../../migrations/0053_collab_owner_fence_grants.ts';
import * as m0054 from '../../migrations/0054_grants_provenance.ts';
import * as m0055 from '../../migrations/0055_min_client_version.ts';

/** Every migration of 03-data-model.md section 14.1, in apply order. */
export const MIGRATIONS: Readonly<Record<string, Migration>> = Object.freeze({
  '0001_users': m0001,
  '0002_user_credentials': m0002,
  '0003_password_setup_tokens': m0003,
  '0004_sessions': m0004,
  '0005_login_throttle': m0005,
  '0006_vaults': m0006,
  '0007_vault_members': m0007,
  '0008_access_tokens': m0008,
  '0009_access_token_vaults': m0009,
  '0010_nodes': m0010,
  '0011_nodes_uq_sibling': m0011,
  '0012_trash_entries': m0012,
  '0013_notes': m0013,
  '0014_note_docs': m0014,
  '0015_note_updates': m0015,
  '0016_note_revisions': m0016,
  '0017_note_projections': m0017,
  '0018_note_projections_fm_indexes': m0018,
  '0019_note_search': m0019,
  '0020_note_search_fulltext': m0020,
  '0021_note_links': m0021,
  '0022_attachments': m0022,
  '0023_jobs': m0023,
  '0024_import_jobs': m0024,
  '0025_export_jobs': m0025,
  '0026_audit_events': m0026,
  '0027_audit_chain_heads': m0027,
  '0028_audit_events_triggers': m0028,
  '0029_audit_events_archive': m0029,
  '0030_access_log': m0030,
  '0031_server_settings': m0031,
  '0032_schema_meta': m0032,
  '0033_desktop_releases': m0033,
  '0034_grants': m0034,
  '0035_oauth_clients': m0035,
  '0036_oauth_clients_grants': m0036,
  '0037_oauth_consents': m0037,
  '0038_oauth_consents_uq_live': m0038,
  '0039_oauth_consents_grants': m0039,
  '0040_oauth_consent_vaults': m0040,
  '0041_oauth_consent_vaults_grants': m0041,
  '0042_oauth_authorization_codes': m0042,
  '0043_oauth_authorization_codes_grants': m0043,
  '0044_oauth_refresh_tokens': m0044,
  '0045_oauth_refresh_tokens_grants': m0045,
  '0046_access_tokens_oauth_columns': m0046,
  '0047_access_tokens_oauth_indexes': m0047,
  '0048_access_log_oauth_client': m0048,
  '0049_admin_users_lock': m0049,
  '0050_session_revocation_commands': m0050,
  '0051_session_revocation_commands_grants': m0051,
  '0052_collab_owner_fence': m0052,
  '0053_collab_owner_fence_grants': m0053,
  '0054_grants_provenance': m0054,
  '0055_min_client_version': m0055,
});

/** The names `/readyz` compares against `kysely_migration`, in apply order. */
export const MIGRATION_NAMES: readonly string[] = Object.freeze(Object.keys(MIGRATIONS));

/** The provider the migrator wrapper hands to Kysely's `Migrator`. */
export const bundledMigrationProvider: MigrationProvider = {
  getMigrations: () => Promise.resolve(MIGRATIONS),
};
