/** Render both DBA grants and the exact-role integration fixture from the product's grant matrix. */
import { fileURLToPath } from 'node:url';

import {
  DB_ROLES,
  GLOBAL_GRANTS,
  GRANT_MATRIX,
  renderGrants,
  SCHEMA_GRANTS,
} from '../apps/server/src/db/grants.ts';
import { runAsMain, type Step } from './lib/step.ts';
import { writeOrCompare } from './lib/write.ts';

const role = (name: keyof typeof DB_ROLES): string =>
  `'${DB_ROLES[name].user}'@'${DB_ROLES[name].host}'`;

function render(): string {
  const statements = [
    `GRANT USAGE ON *.* TO ${role('app')}`,
    `GRANT USAGE ON *.* TO ${role('migrator')}`,
    `GRANT ${GLOBAL_GRANTS.backup.join(', ')} ON *.* TO ${role('backup')}`,
    `GRANT ${SCHEMA_GRANTS.migrator.join(', ')} ON \`iridium\`.* TO ${role('migrator')} WITH GRANT OPTION`,
    `GRANT ${SCHEMA_GRANTS.backup.join(', ')} ON \`iridium\`.* TO ${role('backup')}`,
    ...renderGrants(
      'iridium',
      GRANT_MATRIX.map((row) => row.table),
    ),
  ];
  return (
    '-- Generated by scripts/generate-db-grants.ts from apps/server/src/db/grants.ts.\n' +
    '-- Do not edit; pnpm gen and db-grants.integration enforce this exact role surface.\n\n' +
    statements.map((statement) => `${statement};`).join('\n') +
    '\n'
  );
}

export const step: Step = {
  name: 'database grants',
  produces: 'DBA grants and exact-role grant snapshot',
  async run(context) {
    const output = render();
    return {
      summary: `${String(GRANT_MATRIX.length)} table grants and three exact role definitions`,
      writes: [
        writeOrCompare(
          fileURLToPath(new URL('../docs/ops/db-grants.sql', import.meta.url)),
          output,
          context.check,
        ),
        writeOrCompare(
          fileURLToPath(
            new URL('../apps/server/test/fixtures/db-grants.snapshot.sql', import.meta.url),
          ),
          output,
          context.check,
        ),
      ],
    };
  },
};

if (import.meta.main) await runAsMain(step);
